/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardProjectIdRouteImport } from './routes/dashboard.$projectId'
import { Route as DashboardProjectIdIndexRouteImport } from './routes/dashboard.$projectId.index'
import { Route as DashboardProjectIdSubscriptionsRouteImport } from './routes/dashboard.$projectId.subscriptions'
import { Route as DashboardProjectIdSettingsRouteImport } from './routes/dashboard.$projectId.settings'
import { Route as DashboardProjectIdPlansRouteImport } from './routes/dashboard.$projectId.plans'
import { Route as DashboardProjectIdWebhooksIndexRouteImport } from './routes/dashboard.$projectId/webhooks/index'
import { Route as DashboardProjectIdPlansIndexRouteImport } from './routes/dashboard.$projectId.plans.index'
import { Route as DashboardProjectIdPlansPlanIdRouteImport } from './routes/dashboard.$projectId.plans.$planId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIdRoute = DashboardProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectIdIndexRoute = DashboardProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectIdRoute,
} as any)
const DashboardProjectIdSubscriptionsRoute =
  DashboardProjectIdSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)
const DashboardProjectIdSettingsRoute =
  DashboardProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)
const DashboardProjectIdPlansRoute = DashboardProjectIdPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardProjectIdRoute,
} as any)
const DashboardProjectIdWebhooksIndexRoute =
  DashboardProjectIdWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => DashboardProjectIdRoute,
  } as any)
const DashboardProjectIdPlansIndexRoute =
  DashboardProjectIdPlansIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectIdPlansRoute,
  } as any)
const DashboardProjectIdPlansPlanIdRoute =
  DashboardProjectIdPlansPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => DashboardProjectIdPlansRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectId/plans': typeof DashboardProjectIdPlansRouteWithChildren
  '/dashboard/$projectId/settings': typeof DashboardProjectIdSettingsRoute
  '/dashboard/$projectId/subscriptions': typeof DashboardProjectIdSubscriptionsRoute
  '/dashboard/$projectId/': typeof DashboardProjectIdIndexRoute
  '/dashboard/$projectId/plans/$planId': typeof DashboardProjectIdPlansPlanIdRoute
  '/dashboard/$projectId/plans/': typeof DashboardProjectIdPlansIndexRoute
  '/dashboard/$projectId/webhooks/': typeof DashboardProjectIdWebhooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$projectId/settings': typeof DashboardProjectIdSettingsRoute
  '/dashboard/$projectId/subscriptions': typeof DashboardProjectIdSubscriptionsRoute
  '/dashboard/$projectId': typeof DashboardProjectIdIndexRoute
  '/dashboard/$projectId/plans/$planId': typeof DashboardProjectIdPlansPlanIdRoute
  '/dashboard/$projectId/plans': typeof DashboardProjectIdPlansIndexRoute
  '/dashboard/$projectId/webhooks': typeof DashboardProjectIdWebhooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/$projectId': typeof DashboardProjectIdRouteWithChildren
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectId/plans': typeof DashboardProjectIdPlansRouteWithChildren
  '/dashboard/$projectId/settings': typeof DashboardProjectIdSettingsRoute
  '/dashboard/$projectId/subscriptions': typeof DashboardProjectIdSubscriptionsRoute
  '/dashboard/$projectId/': typeof DashboardProjectIdIndexRoute
  '/dashboard/$projectId/plans/$planId': typeof DashboardProjectIdPlansPlanIdRoute
  '/dashboard/$projectId/plans/': typeof DashboardProjectIdPlansIndexRoute
  '/dashboard/$projectId/webhooks/': typeof DashboardProjectIdWebhooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$projectId'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/$projectId/plans'
    | '/dashboard/$projectId/settings'
    | '/dashboard/$projectId/subscriptions'
    | '/dashboard/$projectId/'
    | '/dashboard/$projectId/plans/$planId'
    | '/dashboard/$projectId/plans/'
    | '/dashboard/$projectId/webhooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/$projectId/settings'
    | '/dashboard/$projectId/subscriptions'
    | '/dashboard/$projectId'
    | '/dashboard/$projectId/plans/$planId'
    | '/dashboard/$projectId/plans'
    | '/dashboard/$projectId/webhooks'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/$projectId'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/$projectId/plans'
    | '/dashboard/$projectId/settings'
    | '/dashboard/$projectId/subscriptions'
    | '/dashboard/$projectId/'
    | '/dashboard/$projectId/plans/$planId'
    | '/dashboard/$projectId/plans/'
    | '/dashboard/$projectId/webhooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$projectId': {
      id: '/dashboard/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof DashboardProjectIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$projectId/': {
      id: '/dashboard/$projectId/'
      path: '/'
      fullPath: '/dashboard/$projectId/'
      preLoaderRoute: typeof DashboardProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/subscriptions': {
      id: '/dashboard/$projectId/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/$projectId/subscriptions'
      preLoaderRoute: typeof DashboardProjectIdSubscriptionsRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/settings': {
      id: '/dashboard/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/plans': {
      id: '/dashboard/$projectId/plans'
      path: '/plans'
      fullPath: '/dashboard/$projectId/plans'
      preLoaderRoute: typeof DashboardProjectIdPlansRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/webhooks/': {
      id: '/dashboard/$projectId/webhooks/'
      path: '/webhooks'
      fullPath: '/dashboard/$projectId/webhooks/'
      preLoaderRoute: typeof DashboardProjectIdWebhooksIndexRouteImport
      parentRoute: typeof DashboardProjectIdRoute
    }
    '/dashboard/$projectId/plans/': {
      id: '/dashboard/$projectId/plans/'
      path: '/'
      fullPath: '/dashboard/$projectId/plans/'
      preLoaderRoute: typeof DashboardProjectIdPlansIndexRouteImport
      parentRoute: typeof DashboardProjectIdPlansRoute
    }
    '/dashboard/$projectId/plans/$planId': {
      id: '/dashboard/$projectId/plans/$planId'
      path: '/$planId'
      fullPath: '/dashboard/$projectId/plans/$planId'
      preLoaderRoute: typeof DashboardProjectIdPlansPlanIdRouteImport
      parentRoute: typeof DashboardProjectIdPlansRoute
    }
  }
}

interface DashboardProjectIdPlansRouteChildren {
  DashboardProjectIdPlansPlanIdRoute: typeof DashboardProjectIdPlansPlanIdRoute
  DashboardProjectIdPlansIndexRoute: typeof DashboardProjectIdPlansIndexRoute
}

const DashboardProjectIdPlansRouteChildren: DashboardProjectIdPlansRouteChildren =
  {
    DashboardProjectIdPlansPlanIdRoute: DashboardProjectIdPlansPlanIdRoute,
    DashboardProjectIdPlansIndexRoute: DashboardProjectIdPlansIndexRoute,
  }

const DashboardProjectIdPlansRouteWithChildren =
  DashboardProjectIdPlansRoute._addFileChildren(
    DashboardProjectIdPlansRouteChildren,
  )

interface DashboardProjectIdRouteChildren {
  DashboardProjectIdPlansRoute: typeof DashboardProjectIdPlansRouteWithChildren
  DashboardProjectIdSettingsRoute: typeof DashboardProjectIdSettingsRoute
  DashboardProjectIdSubscriptionsRoute: typeof DashboardProjectIdSubscriptionsRoute
  DashboardProjectIdIndexRoute: typeof DashboardProjectIdIndexRoute
  DashboardProjectIdWebhooksIndexRoute: typeof DashboardProjectIdWebhooksIndexRoute
}

const DashboardProjectIdRouteChildren: DashboardProjectIdRouteChildren = {
  DashboardProjectIdPlansRoute: DashboardProjectIdPlansRouteWithChildren,
  DashboardProjectIdSettingsRoute: DashboardProjectIdSettingsRoute,
  DashboardProjectIdSubscriptionsRoute: DashboardProjectIdSubscriptionsRoute,
  DashboardProjectIdIndexRoute: DashboardProjectIdIndexRoute,
  DashboardProjectIdWebhooksIndexRoute: DashboardProjectIdWebhooksIndexRoute,
}

const DashboardProjectIdRouteWithChildren =
  DashboardProjectIdRoute._addFileChildren(DashboardProjectIdRouteChildren)

interface DashboardRouteChildren {
  DashboardProjectIdRoute: typeof DashboardProjectIdRouteWithChildren
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectIdRoute: DashboardProjectIdRouteWithChildren,
  DashboardNewRoute: DashboardNewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
